### ISSUE TITLE
Some invalid IDs shown as valid

### ISSUE THREAD

**Issue by slawa-dev** [bhomnick/identitytw#15]
https://v.identity.tw/?id=A300000005

Problem is the regex:
`ID_REGEX = "^[A-Z]{1}[A-D0-9]{1}[0-9]{8}$";`

Second character can only be one of those 1,2,8,9,A,B,C,D

**Comment by slawa-dev** [comment]
This would work
`ID_REGEX = "^[A-Z]{1}[1-2A-D8-9]{1}[0-9]{8}$";`

**Comment by fifieldt** [comment]
Apparently this is still not fixed on the live site.
